CREATE TABLE `bookings` (
  `booking_id` char(36) NOT NULL,
  `user_id` char(36) DEFAULT NULL,
  `vehicle_id` char(36) DEFAULT NULL,
  `pickup_location` varchar(255) DEFAULT NULL,
  `pickup_lat` decimal(10,7) DEFAULT NULL,
  `pickup_lng` decimal(10,7) DEFAULT NULL,
  `dropoff_location` varchar(255) DEFAULT NULL,
  `dropoff_lat` decimal(10,7) DEFAULT NULL,
  `dropoff_lng` decimal(10,7) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `time` time DEFAULT NULL,
  `total_distance` decimal(10,2) DEFAULT NULL,
  `total_price` decimal(10,2) DEFAULT NULL,
  `total_weight` int DEFAULT NULL,
  `items_count` int DEFAULT NULL,
  `status` enum('pending','confirmed','in_progress','in_transit','completed','cancelled') DEFAULT 'pending',
  `payment_method` enum('cash','gcash','maya') DEFAULT 'cash',
  `notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `dropoff_time` varchar(45) DEFAULT NULL,
  `pickup_time` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`booking_id`),
  KEY `vehicle_id` (`vehicle_id`),
  CONSTRAINT `bookings_ibfk_1` FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles` (`vehicleid`) ON DELETE SET NULL ON UPDATE CASCADE
);